// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_common_10000.proto

package com.ohayoo.whitebird.generate.message;

public final class CommonMessage {
  private CommonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     *
     * <pre>
     * 正常状态
     * </pre>
     */
    SUCCESS(0, 0),
    /**
     * <code>NoLogicServer = 1;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    NoLogicServer(1, 1),
    /**
     * <code>SessionLoginInvalid = 2;</code>
     *
     * <pre>
     * session登录失效
     * </pre>
     */
    SessionLoginInvalid(2, 2),
    /**
     * <code>ExcelDataError = 3;</code>
     *
     * <pre>
     * 策划表数据错误
     * </pre>
     */
    ExcelDataError(3, 3),
    /**
     * <code>ServerInnerException = 4;</code>
     *
     * <pre>
     * 服务器异常错误
     * </pre>
     */
    ServerInnerException(4, 4),
    /**
     * <code>MsgNotFoundException = 5;</code>
     *
     * <pre>
     * 消息未注册
     * </pre>
     */
    MsgNotFoundException(5, 5),
    /**
     * <code>ParamErrorException = 6;</code>
     *
     * <pre>
     * 基础参数错误
     * </pre>
     */
    ParamErrorException(6, 6),
    /**
     * <code>TokenErrorException = 7;</code>
     *
     * <pre>
     * token失效
     * </pre>
     */
    TokenErrorException(7, 7),
    /**
     * <code>RenameCdErrorException = 8;</code>
     *
     * <pre>
     * 改名cd还没到
     * </pre>
     */
    RenameCdErrorException(8, 8),
    /**
     * <code>Energy_No_Enough_Exception = 1001;</code>
     *
     * <pre>
     *chapter
     * </pre>
     */
    Energy_No_Enough_Exception(9, 1001),
    /**
     * <code>Function_No_Open_Exception = 1102;</code>
     *
     * <pre>
     *开关
     * </pre>
     */
    Function_No_Open_Exception(10, 1102),
    /**
     * <code>COIN_NO_ENOUGH = 1103;</code>
     *
     * <pre>
     * 金币不足
     * </pre>
     */
    COIN_NO_ENOUGH(11, 1103),
    /**
     * <code>BAO_SHI_NO_ENOUGH = 1104;</code>
     *
     * <pre>
     * 宝石不足
     * </pre>
     */
    BAO_SHI_NO_ENOUGH(12, 1104),
    /**
     * <code>CARD_PRICE_NO_ENOUGH = 1105;</code>
     *
     * <pre>
     * 卡牌碎片不足
     * </pre>
     */
    CARD_PRICE_NO_ENOUGH(13, 1105),
    /**
     * <code>SKILL_PRICE_NO_ENOUGH = 1106;</code>
     *
     * <pre>
     * 主技能碎片不足
     * </pre>
     */
    SKILL_PRICE_NO_ENOUGH(14, 1106),
    /**
     * <code>BONUS_ALREADY_GIVE = 1107;</code>
     *
     * <pre>
     * 奖励已经领取
     * </pre>
     */
    BONUS_ALREADY_GIVE(15, 1107),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     *
     * <pre>
     * 正常状态
     * </pre>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>NoLogicServer = 1;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    public static final int NoLogicServer_VALUE = 1;
    /**
     * <code>SessionLoginInvalid = 2;</code>
     *
     * <pre>
     * session登录失效
     * </pre>
     */
    public static final int SessionLoginInvalid_VALUE = 2;
    /**
     * <code>ExcelDataError = 3;</code>
     *
     * <pre>
     * 策划表数据错误
     * </pre>
     */
    public static final int ExcelDataError_VALUE = 3;
    /**
     * <code>ServerInnerException = 4;</code>
     *
     * <pre>
     * 服务器异常错误
     * </pre>
     */
    public static final int ServerInnerException_VALUE = 4;
    /**
     * <code>MsgNotFoundException = 5;</code>
     *
     * <pre>
     * 消息未注册
     * </pre>
     */
    public static final int MsgNotFoundException_VALUE = 5;
    /**
     * <code>ParamErrorException = 6;</code>
     *
     * <pre>
     * 基础参数错误
     * </pre>
     */
    public static final int ParamErrorException_VALUE = 6;
    /**
     * <code>TokenErrorException = 7;</code>
     *
     * <pre>
     * token失效
     * </pre>
     */
    public static final int TokenErrorException_VALUE = 7;
    /**
     * <code>RenameCdErrorException = 8;</code>
     *
     * <pre>
     * 改名cd还没到
     * </pre>
     */
    public static final int RenameCdErrorException_VALUE = 8;
    /**
     * <code>Energy_No_Enough_Exception = 1001;</code>
     *
     * <pre>
     *chapter
     * </pre>
     */
    public static final int Energy_No_Enough_Exception_VALUE = 1001;
    /**
     * <code>Function_No_Open_Exception = 1102;</code>
     *
     * <pre>
     *开关
     * </pre>
     */
    public static final int Function_No_Open_Exception_VALUE = 1102;
    /**
     * <code>COIN_NO_ENOUGH = 1103;</code>
     *
     * <pre>
     * 金币不足
     * </pre>
     */
    public static final int COIN_NO_ENOUGH_VALUE = 1103;
    /**
     * <code>BAO_SHI_NO_ENOUGH = 1104;</code>
     *
     * <pre>
     * 宝石不足
     * </pre>
     */
    public static final int BAO_SHI_NO_ENOUGH_VALUE = 1104;
    /**
     * <code>CARD_PRICE_NO_ENOUGH = 1105;</code>
     *
     * <pre>
     * 卡牌碎片不足
     * </pre>
     */
    public static final int CARD_PRICE_NO_ENOUGH_VALUE = 1105;
    /**
     * <code>SKILL_PRICE_NO_ENOUGH = 1106;</code>
     *
     * <pre>
     * 主技能碎片不足
     * </pre>
     */
    public static final int SKILL_PRICE_NO_ENOUGH_VALUE = 1106;
    /**
     * <code>BONUS_ALREADY_GIVE = 1107;</code>
     *
     * <pre>
     * 奖励已经领取
     * </pre>
     */
    public static final int BONUS_ALREADY_GIVE_VALUE = 1107;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return NoLogicServer;
        case 2: return SessionLoginInvalid;
        case 3: return ExcelDataError;
        case 4: return ServerInnerException;
        case 5: return MsgNotFoundException;
        case 6: return ParamErrorException;
        case 7: return TokenErrorException;
        case 8: return RenameCdErrorException;
        case 1001: return Energy_No_Enough_Exception;
        case 1102: return Function_No_Open_Exception;
        case 1103: return COIN_NO_ENOUGH;
        case 1104: return BAO_SHI_NO_ENOUGH;
        case 1105: return CARD_PRICE_NO_ENOUGH;
        case 1106: return SKILL_PRICE_NO_ENOUGH;
        case 1107: return BONUS_ALREADY_GIVE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorCode)
  }

  /**
   * Protobuf enum {@code HeaderType}
   */
  public enum HeaderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>token = 0;</code>
     *
     * <pre>
     * 正常状态
     * </pre>
     */
    token(0, 0),
    /**
     * <code>message_id = 1;</code>
     *
     * <pre>
     * 请求的消息ID 、 回传客户端请求的消息ID
     * </pre>
     */
    message_id(1, 1),
    /**
     * <code>response_message_id = 2;</code>
     *
     * <pre>
     * 下发的消息ID
     * </pre>
     */
    response_message_id(2, 2),
    /**
     * <code>status_code = 3;</code>
     *
     * <pre>
     * 响应状态码
     * </pre>
     */
    status_code(3, 3),
    /**
     * <code>response_server_time = 4;</code>
     *
     * <pre>
     * 服务器响应时间戳
     * </pre>
     */
    response_server_time(4, 4),
    /**
     * <code>collect_time = 5;</code>
     *
     * <pre>
     * 服务器处理耗时
     * </pre>
     */
    collect_time(5, 5),
    ;

    /**
     * <code>token = 0;</code>
     *
     * <pre>
     * 正常状态
     * </pre>
     */
    public static final int token_VALUE = 0;
    /**
     * <code>message_id = 1;</code>
     *
     * <pre>
     * 请求的消息ID 、 回传客户端请求的消息ID
     * </pre>
     */
    public static final int message_id_VALUE = 1;
    /**
     * <code>response_message_id = 2;</code>
     *
     * <pre>
     * 下发的消息ID
     * </pre>
     */
    public static final int response_message_id_VALUE = 2;
    /**
     * <code>status_code = 3;</code>
     *
     * <pre>
     * 响应状态码
     * </pre>
     */
    public static final int status_code_VALUE = 3;
    /**
     * <code>response_server_time = 4;</code>
     *
     * <pre>
     * 服务器响应时间戳
     * </pre>
     */
    public static final int response_server_time_VALUE = 4;
    /**
     * <code>collect_time = 5;</code>
     *
     * <pre>
     * 服务器处理耗时
     * </pre>
     */
    public static final int collect_time_VALUE = 5;


    public final int getNumber() { return value; }

    public static HeaderType valueOf(int value) {
      switch (value) {
        case 0: return token;
        case 1: return message_id;
        case 2: return response_message_id;
        case 3: return status_code;
        case 4: return response_server_time;
        case 5: return collect_time;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<HeaderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<HeaderType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<HeaderType>() {
            public HeaderType findValueByNumber(int number) {
              return HeaderType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final HeaderType[] VALUES = values();

    public static HeaderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private HeaderType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:HeaderType)
  }

  public interface PBErrorDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBErrorDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    boolean hasCommandId();
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    int getCommandId();

    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code PBErrorDown}
   *
   * <pre>
   * 错误回复
   * </pre>
   */
  public static final class PBErrorDown extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBErrorDown)
      PBErrorDownOrBuilder {
    // Use PBErrorDown.newBuilder() to construct.
    private PBErrorDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBErrorDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBErrorDown defaultInstance;
    public static PBErrorDown getDefaultInstance() {
      return defaultInstance;
    }

    public PBErrorDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBErrorDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBErrorDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBErrorDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.Builder.class);
    }

    public static com.google.protobuf.Parser<PBErrorDown> PARSER =
        new com.google.protobuf.AbstractParser<PBErrorDown>() {
      public PBErrorDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBErrorDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBErrorDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    public int getCommandId() {
      return commandId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      commandId_ = 0;
      errorCode_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBErrorDown}
     *
     * <pre>
     * 错误回复
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBErrorDown)
        com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBErrorDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBErrorDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.Builder.class);
      }

      // Construct using com.ohayoo.dogwar.generate.message.CommonMessage.PBErrorDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBErrorDown_descriptor;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown getDefaultInstanceForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.getDefaultInstance();
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown build() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown buildPartial() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown result = new com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown) {
          return mergeFrom((com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown other) {
        if (other == com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.getDefaultInstance()) return this;
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int commandId_ ;
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public Builder setCommandId(int value) {
        bitField0_ |= 0x00000001;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBErrorDown)
    }

    static {
      defaultInstance = new PBErrorDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBErrorDown)
  }

  public interface PBGmCmdUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBGmCmdUp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string param = 1;</code>
     */
    boolean hasParam();
    /**
     * <code>optional string param = 1;</code>
     */
    java.lang.String getParam();
    /**
     * <code>optional string param = 1;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();
  }
  /**
   * Protobuf type {@code PBGmCmdUp}
   */
  public static final class PBGmCmdUp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBGmCmdUp)
      PBGmCmdUpOrBuilder {
    // Use PBGmCmdUp.newBuilder() to construct.
    private PBGmCmdUp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBGmCmdUp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBGmCmdUp defaultInstance;
    public static PBGmCmdUp getDefaultInstance() {
      return defaultInstance;
    }

    public PBGmCmdUp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBGmCmdUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              param_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.Builder.class);
    }

    public static com.google.protobuf.Parser<PBGmCmdUp> PARSER =
        new com.google.protobuf.AbstractParser<PBGmCmdUp>() {
      public PBGmCmdUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBGmCmdUp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBGmCmdUp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PARAM_FIELD_NUMBER = 1;
    private java.lang.Object param_;
    /**
     * <code>optional string param = 1;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string param = 1;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string param = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      param_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getParamBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getParamBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBGmCmdUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBGmCmdUp)
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.Builder.class);
      }

      // Construct using com.ohayoo.dogwar.generate.message.CommonMessage.PBGmCmdUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdUp_descriptor;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp getDefaultInstanceForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.getDefaultInstance();
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp build() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp buildPartial() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp result = new com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp) {
          return mergeFrom((com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp other) {
        if (other == com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.getDefaultInstance()) return this;
        if (other.hasParam()) {
          bitField0_ |= 0x00000001;
          param_ = other.param_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object param_ = "";
      /**
       * <code>optional string param = 1;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            param_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000001);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 1;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        param_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBGmCmdUp)
    }

    static {
      defaultInstance = new PBGmCmdUp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBGmCmdUp)
  }

  public interface PBGmCmdDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBGmCmdDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code PBGmCmdDown}
   */
  public static final class PBGmCmdDown extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBGmCmdDown)
      PBGmCmdDownOrBuilder {
    // Use PBGmCmdDown.newBuilder() to construct.
    private PBGmCmdDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBGmCmdDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBGmCmdDown defaultInstance;
    public static PBGmCmdDown getDefaultInstance() {
      return defaultInstance;
    }

    public PBGmCmdDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBGmCmdDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.Builder.class);
    }

    public static com.google.protobuf.Parser<PBGmCmdDown> PARSER =
        new com.google.protobuf.AbstractParser<PBGmCmdDown>() {
      public PBGmCmdDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBGmCmdDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBGmCmdDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    public boolean getResult() {
      return result_;
    }

    private void initFields() {
      result_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBGmCmdDown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBGmCmdDown)
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.class, com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.Builder.class);
      }

      // Construct using com.ohayoo.dogwar.generate.message.CommonMessage.PBGmCmdDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.internal_static_PBGmCmdDown_descriptor;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown getDefaultInstanceForType() {
        return com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.getDefaultInstance();
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown build() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown buildPartial() {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown result = new com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown) {
          return mergeFrom((com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown other) {
        if (other == com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBGmCmdDown)
    }

    static {
      defaultInstance = new PBGmCmdDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBGmCmdDown)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBErrorDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBErrorDown_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBGmCmdUp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBGmCmdUp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBGmCmdDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBGmCmdDown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026msg_common_10000.proto\032\roptions.proto\"" +
      "J\n\013PBErrorDown\022\021\n\tcommandId\030\001 \001(\005\022\021\n\terr" +
      "orCode\030\002 \001(\005\022\017\n\007message\030\003 \001(\t:\004\300>\220N\" \n\tP" +
      "BGmCmdUp\022\r\n\005param\030\001 \001(\t:\004\300>\221N\"#\n\013PBGmCmd" +
      "Down\022\016\n\006result\030\001 \001(\010:\004\300>\222N*\231\003\n\tErrorCode" +
      "\022\013\n\007SUCCESS\020\000\022\021\n\rNoLogicServer\020\001\022\027\n\023Sess" +
      "ionLoginInvalid\020\002\022\022\n\016ExcelDataError\020\003\022\030\n" +
      "\024ServerInnerException\020\004\022\030\n\024MsgNotFoundEx" +
      "ception\020\005\022\027\n\023ParamErrorException\020\006\022\027\n\023To" +
      "kenErrorException\020\007\022\032\n\026RenameCdErrorExce",
      "ption\020\010\022\037\n\032Energy_No_Enough_Exception\020\351\007" +
      "\022\037\n\032Function_No_Open_Exception\020\316\010\022\023\n\016COI" +
      "N_NO_ENOUGH\020\317\010\022\026\n\021BAO_SHI_NO_ENOUGH\020\320\010\022\031" +
      "\n\024CARD_PRICE_NO_ENOUGH\020\321\010\022\032\n\025SKILL_PRICE" +
      "_NO_ENOUGH\020\322\010\022\027\n\022BONUS_ALREADY_GIVE\020\323\010*}" +
      "\n\nHeaderType\022\t\n\005token\020\000\022\016\n\nmessage_id\020\001\022" +
      "\027\n\023response_message_id\020\002\022\017\n\013status_code\020" +
      "\003\022\030\n\024response_server_time\020\004\022\020\n\014collect_t" +
      "ime\020\005B5\n\"com.ohayoo.dogwar.generate.mess" +
      "ageB\rCommonMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ohayoo.whitebird.generate.message.Options.getDescriptor(),
        }, assigner);
    internal_static_PBErrorDown_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PBErrorDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBErrorDown_descriptor,
        new java.lang.String[] { "CommandId", "ErrorCode", "Message", });
    internal_static_PBGmCmdUp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PBGmCmdUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBGmCmdUp_descriptor,
        new java.lang.String[] { "Param", });
    internal_static_PBGmCmdDown_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PBGmCmdDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBGmCmdDown_descriptor,
        new java.lang.String[] { "Result", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.ohayoo.whitebird.generate.message.Options.msgId);
    registry.add(com.ohayoo.whitebird.generate.message.Options.msgId);
    registry.add(com.ohayoo.whitebird.generate.message.Options.msgId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.ohayoo.whitebird.generate.message.Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
