// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msg_common_10000.proto

package io.github.viakiba.hinx.generate.message;

public final class CommonMessage {
  private CommonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NULL = 0;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    NULL(0, 0),
    /**
     * <code>NoLogicServer = 1;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    NoLogicServer(1, 1),
    /**
     * <code>SessionLoginInvalid = 2;</code>
     *
     * <pre>
     * session登录失效
     * </pre>
     */
    SessionLoginInvalid(2, 2),
    /**
     * <code>PrototypeDataError = 3;</code>
     *
     * <pre>
     * 策划表数据错误
     * </pre>
     */
    PrototypeDataError(3, 3),
    /**
     * <code>ServerException = 4;</code>
     *
     * <pre>
     * 服务器异常错误
     * </pre>
     */
    ServerException(4, 4),
    /**
     * <code>MsgNotFoundException = 5;</code>
     *
     * <pre>
     * 消息未注册
     * </pre>
     */
    MsgNotFoundException(5, 5),
    ;

    /**
     * <code>NULL = 0;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    public static final int NULL_VALUE = 0;
    /**
     * <code>NoLogicServer = 1;</code>
     *
     * <pre>
     * 无服务可用
     * </pre>
     */
    public static final int NoLogicServer_VALUE = 1;
    /**
     * <code>SessionLoginInvalid = 2;</code>
     *
     * <pre>
     * session登录失效
     * </pre>
     */
    public static final int SessionLoginInvalid_VALUE = 2;
    /**
     * <code>PrototypeDataError = 3;</code>
     *
     * <pre>
     * 策划表数据错误
     * </pre>
     */
    public static final int PrototypeDataError_VALUE = 3;
    /**
     * <code>ServerException = 4;</code>
     *
     * <pre>
     * 服务器异常错误
     * </pre>
     */
    public static final int ServerException_VALUE = 4;
    /**
     * <code>MsgNotFoundException = 5;</code>
     *
     * <pre>
     * 消息未注册
     * </pre>
     */
    public static final int MsgNotFoundException_VALUE = 5;


    public final int getNumber() { return value; }

    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 0: return NULL;
        case 1: return NoLogicServer;
        case 2: return SessionLoginInvalid;
        case 3: return PrototypeDataError;
        case 4: return ServerException;
        case 5: return MsgNotFoundException;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return CommonMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ErrorCode)
  }

  public interface PBErrorDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBErrorDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    boolean hasCommandId();
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    int getCommandId();

    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    boolean hasErrorCode();
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    int getErrorCode();

    /**
     * <code>optional string message = 3;</code>
     */
    boolean hasMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>optional string message = 3;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code PBErrorDown}
   *
   * <pre>
   * 错误回复
   * </pre>
   */
  public static final class PBErrorDown extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBErrorDown)
      PBErrorDownOrBuilder {
    // Use PBErrorDown.newBuilder() to construct.
    private PBErrorDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBErrorDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBErrorDown defaultInstance;
    public static PBErrorDown getDefaultInstance() {
      return defaultInstance;
    }

    public PBErrorDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBErrorDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              commandId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              errorCode_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              message_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonMessage.internal_static_PBErrorDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonMessage.internal_static_PBErrorDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommonMessage.PBErrorDown.class, CommonMessage.PBErrorDown.Builder.class);
    }

    public static com.google.protobuf.Parser<PBErrorDown> PARSER =
        new com.google.protobuf.AbstractParser<PBErrorDown>() {
      public PBErrorDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBErrorDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBErrorDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMANDID_FIELD_NUMBER = 1;
    private int commandId_;
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    public boolean hasCommandId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 commandId = 1;</code>
     *
     * <pre>
     *返回请求的指令
     * </pre>
     */
    public int getCommandId() {
      return commandId_;
    }

    public static final int ERRORCODE_FIELD_NUMBER = 2;
    private int errorCode_;
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public boolean hasErrorCode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 errorCode = 2;</code>
     */
    public int getErrorCode() {
      return errorCode_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private java.lang.Object message_;
    /**
     * <code>optional string message = 3;</code>
     */
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string message = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      commandId_ = 0;
      errorCode_ = 0;
      message_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, commandId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, errorCode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBErrorDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBErrorDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBErrorDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBErrorDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBErrorDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CommonMessage.PBErrorDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBErrorDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CommonMessage.PBErrorDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBErrorDown}
     *
     * <pre>
     * 错误回复
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBErrorDown)
        CommonMessage.PBErrorDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonMessage.internal_static_PBErrorDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonMessage.internal_static_PBErrorDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommonMessage.PBErrorDown.class, CommonMessage.PBErrorDown.Builder.class);
      }

      // Construct using com.ohayoo.whitebird.generate.message.CommonMessage.PBErrorDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        commandId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        message_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonMessage.internal_static_PBErrorDown_descriptor;
      }

      public CommonMessage.PBErrorDown getDefaultInstanceForType() {
        return CommonMessage.PBErrorDown.getDefaultInstance();
      }

      public CommonMessage.PBErrorDown build() {
        CommonMessage.PBErrorDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommonMessage.PBErrorDown buildPartial() {
        CommonMessage.PBErrorDown result = new CommonMessage.PBErrorDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandId_ = commandId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorCode_ = errorCode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.message_ = message_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommonMessage.PBErrorDown) {
          return mergeFrom((CommonMessage.PBErrorDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommonMessage.PBErrorDown other) {
        if (other == CommonMessage.PBErrorDown.getDefaultInstance()) return this;
        if (other.hasCommandId()) {
          setCommandId(other.getCommandId());
        }
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasMessage()) {
          bitField0_ |= 0x00000004;
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommonMessage.PBErrorDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommonMessage.PBErrorDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int commandId_ ;
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public boolean hasCommandId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public int getCommandId() {
        return commandId_;
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public Builder setCommandId(int value) {
        bitField0_ |= 0x00000001;
        commandId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 commandId = 1;</code>
       *
       * <pre>
       *返回请求的指令
       * </pre>
       */
      public Builder clearCommandId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandId_ = 0;
        onChanged();
        return this;
      }

      private int errorCode_ ;
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public boolean hasErrorCode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public int getErrorCode() {
        return errorCode_;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder setErrorCode(int value) {
        bitField0_ |= 0x00000002;
        errorCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errorCode = 2;</code>
       */
      public Builder clearErrorCode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>optional string message = 3;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder clearMessage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string message = 3;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        message_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBErrorDown)
    }

    static {
      defaultInstance = new PBErrorDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBErrorDown)
  }

  public interface PBGmCmdUpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBGmCmdUp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     *1:给钱(ModifyCurrency)
     * </pre>
     */
    boolean hasCmd();
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     *1:给钱(ModifyCurrency)
     * </pre>
     */
    int getCmd();

    /**
     * <code>optional string param = 2;</code>
     */
    boolean hasParam();
    /**
     * <code>optional string param = 2;</code>
     */
    java.lang.String getParam();
    /**
     * <code>optional string param = 2;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes();
  }
  /**
   * Protobuf type {@code PBGmCmdUp}
   */
  public static final class PBGmCmdUp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBGmCmdUp)
      PBGmCmdUpOrBuilder {
    // Use PBGmCmdUp.newBuilder() to construct.
    private PBGmCmdUp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBGmCmdUp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBGmCmdUp defaultInstance;
    public static PBGmCmdUp getDefaultInstance() {
      return defaultInstance;
    }

    public PBGmCmdUp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBGmCmdUp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cmd_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              param_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonMessage.internal_static_PBGmCmdUp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonMessage.internal_static_PBGmCmdUp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommonMessage.PBGmCmdUp.class, CommonMessage.PBGmCmdUp.Builder.class);
    }

    public static com.google.protobuf.Parser<PBGmCmdUp> PARSER =
        new com.google.protobuf.AbstractParser<PBGmCmdUp>() {
      public PBGmCmdUp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBGmCmdUp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBGmCmdUp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     *1:给钱(ModifyCurrency)
     * </pre>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 cmd = 1;</code>
     *
     * <pre>
     *1:给钱(ModifyCurrency)
     * </pre>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int PARAM_FIELD_NUMBER = 2;
    private java.lang.Object param_;
    /**
     * <code>optional string param = 2;</code>
     */
    public boolean hasParam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string param = 2;</code>
     */
    public java.lang.String getParam() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          param_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string param = 2;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes() {
      java.lang.Object ref = param_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        param_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      cmd_ = 0;
      param_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getParamBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParamBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdUp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CommonMessage.PBGmCmdUp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBGmCmdUp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CommonMessage.PBGmCmdUp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBGmCmdUp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBGmCmdUp)
        CommonMessage.PBGmCmdUpOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonMessage.internal_static_PBGmCmdUp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonMessage.internal_static_PBGmCmdUp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommonMessage.PBGmCmdUp.class, CommonMessage.PBGmCmdUp.Builder.class);
      }

      // Construct using com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdUp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        param_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonMessage.internal_static_PBGmCmdUp_descriptor;
      }

      public CommonMessage.PBGmCmdUp getDefaultInstanceForType() {
        return CommonMessage.PBGmCmdUp.getDefaultInstance();
      }

      public CommonMessage.PBGmCmdUp build() {
        CommonMessage.PBGmCmdUp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommonMessage.PBGmCmdUp buildPartial() {
        CommonMessage.PBGmCmdUp result = new CommonMessage.PBGmCmdUp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommonMessage.PBGmCmdUp) {
          return mergeFrom((CommonMessage.PBGmCmdUp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommonMessage.PBGmCmdUp other) {
        if (other == CommonMessage.PBGmCmdUp.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasParam()) {
          bitField0_ |= 0x00000002;
          param_ = other.param_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommonMessage.PBGmCmdUp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommonMessage.PBGmCmdUp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cmd_ ;
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       *1:给钱(ModifyCurrency)
       * </pre>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       *1:给钱(ModifyCurrency)
       * </pre>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       *1:给钱(ModifyCurrency)
       * </pre>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cmd = 1;</code>
       *
       * <pre>
       *1:给钱(ModifyCurrency)
       * </pre>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object param_ = "";
      /**
       * <code>optional string param = 2;</code>
       */
      public boolean hasParam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string param = 2;</code>
       */
      public java.lang.String getParam() {
        java.lang.Object ref = param_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            param_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string param = 2;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes() {
        java.lang.Object ref = param_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          param_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string param = 2;</code>
       */
      public Builder setParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        param_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 2;</code>
       */
      public Builder clearParam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        param_ = getDefaultInstance().getParam();
        onChanged();
        return this;
      }
      /**
       * <code>optional string param = 2;</code>
       */
      public Builder setParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        param_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBGmCmdUp)
    }

    static {
      defaultInstance = new PBGmCmdUp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBGmCmdUp)
  }

  public interface PBGmCmdDownOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PBGmCmdDown)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    boolean hasResult();
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    boolean getResult();
  }
  /**
   * Protobuf type {@code PBGmCmdDown}
   */
  public static final class PBGmCmdDown extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PBGmCmdDown)
      PBGmCmdDownOrBuilder {
    // Use PBGmCmdDown.newBuilder() to construct.
    private PBGmCmdDown(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBGmCmdDown(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBGmCmdDown defaultInstance;
    public static PBGmCmdDown getDefaultInstance() {
      return defaultInstance;
    }

    public PBGmCmdDown getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBGmCmdDown(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              result_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CommonMessage.internal_static_PBGmCmdDown_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CommonMessage.internal_static_PBGmCmdDown_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CommonMessage.PBGmCmdDown.class, CommonMessage.PBGmCmdDown.Builder.class);
    }

    public static com.google.protobuf.Parser<PBGmCmdDown> PARSER =
        new com.google.protobuf.AbstractParser<PBGmCmdDown>() {
      public PBGmCmdDown parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBGmCmdDown(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBGmCmdDown> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int RESULT_FIELD_NUMBER = 1;
    private boolean result_;
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional bool result = 1;</code>
     *
     * <pre>
     * true(成功) false(失败)
     * </pre>
     */
    public boolean getResult() {
      return result_;
    }

    private void initFields() {
      result_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, result_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, result_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdDown parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static CommonMessage.PBGmCmdDown parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static CommonMessage.PBGmCmdDown parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(CommonMessage.PBGmCmdDown prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PBGmCmdDown}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PBGmCmdDown)
        CommonMessage.PBGmCmdDownOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CommonMessage.internal_static_PBGmCmdDown_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CommonMessage.internal_static_PBGmCmdDown_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CommonMessage.PBGmCmdDown.class, CommonMessage.PBGmCmdDown.Builder.class);
      }

      // Construct using com.ohayoo.whitebird.generate.message.CommonMessage.PBGmCmdDown.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CommonMessage.internal_static_PBGmCmdDown_descriptor;
      }

      public CommonMessage.PBGmCmdDown getDefaultInstanceForType() {
        return CommonMessage.PBGmCmdDown.getDefaultInstance();
      }

      public CommonMessage.PBGmCmdDown build() {
        CommonMessage.PBGmCmdDown result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public CommonMessage.PBGmCmdDown buildPartial() {
        CommonMessage.PBGmCmdDown result = new CommonMessage.PBGmCmdDown(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CommonMessage.PBGmCmdDown) {
          return mergeFrom((CommonMessage.PBGmCmdDown)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CommonMessage.PBGmCmdDown other) {
        if (other == CommonMessage.PBGmCmdDown.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        CommonMessage.PBGmCmdDown parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (CommonMessage.PBGmCmdDown) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean result_ ;
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public Builder setResult(boolean value) {
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 1;</code>
       *
       * <pre>
       * true(成功) false(失败)
       * </pre>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PBGmCmdDown)
    }

    static {
      defaultInstance = new PBGmCmdDown(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PBGmCmdDown)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBErrorDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBErrorDown_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBGmCmdUp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBGmCmdUp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PBGmCmdDown_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PBGmCmdDown_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026msg_common_10000.proto\032\roptions.proto\"" +
      "J\n\013PBErrorDown\022\021\n\tcommandId\030\001 \001(\005\022\021\n\terr" +
      "orCode\030\002 \001(\005\022\017\n\007message\030\003 \001(\t:\004\300>\220N\"-\n\tP" +
      "BGmCmdUp\022\013\n\003cmd\030\001 \001(\005\022\r\n\005param\030\002 \001(\t:\004\300>" +
      "\221N\"#\n\013PBGmCmdDown\022\016\n\006result\030\001 \001(\010:\004\300>\222N*" +
      "\210\001\n\tErrorCode\022\010\n\004NULL\020\000\022\021\n\rNoLogicServer" +
      "\020\001\022\027\n\023SessionLoginInvalid\020\002\022\026\n\022Prototype" +
      "DataError\020\003\022\023\n\017ServerException\020\004\022\030\n\024MsgN" +
      "otFoundException\020\005B8\n%com.ohayoo.whitebi" +
      "rd.generate.messageB\rCommonMessageH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Options.getDescriptor(),
        }, assigner);
    internal_static_PBErrorDown_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PBErrorDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBErrorDown_descriptor,
        new java.lang.String[] { "CommandId", "ErrorCode", "Message", });
    internal_static_PBGmCmdUp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PBGmCmdUp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBGmCmdUp_descriptor,
        new java.lang.String[] { "Cmd", "Param", });
    internal_static_PBGmCmdDown_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PBGmCmdDown_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PBGmCmdDown_descriptor,
        new java.lang.String[] { "Result", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(Options.msgId);
    registry.add(Options.msgId);
    registry.add(Options.msgId);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    Options.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
